import React, { useState } from 'react';
import './BasicDetails.css';

function ReportingForm() {
  const [formData, setFormData] = useState({
    employeeId: '',
    reportType: '',
    reportDate: '',
    description: '',
    generatedBy: '',
    uploadAttachment: null,
  });

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (name === 'uploadAttachment') {
      setFormData({ ...formData, uploadAttachment: files[0] });
    } else {
      setFormData({ ...formData, [name]: value });
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log('Submitted Report:', formData);
    alert('Report Submitted Successfully!');
  };

  return (
    <div className="basic-details-form">
      <h2>Submit Report</h2>
      <form onSubmit={handleSubmit}>
        <label>Employee ID:</label>
        <input name="employeeId" value={formData.employeeId} onChange={handleChange} required />

        <label>Report Type:</label>
        <select name="reportType" value={formData.reportType} onChange={handleChange} required>
          <option value="">Select</option>
          <option value="Performance">Performance</option>
          <option value="Attendance">Attendance</option>
          <option value="Violation">Violation</option>
          <option value="General Feedback">General Feedback</option>
        </select>

        <label>Date of Report:</label>
        <input
          type="date"
          name="reportDate"
          value={formData.reportDate}
          onChange={handleChange}
          required
        />

        <label>Description / Summary:</label>
        <textarea
          name="description"
          value={formData.description}
          onChange={handleChange}
          rows={4}
          required
        />

        <label>Generated By:</label>
        <input name="generatedBy" value={formData.generatedBy} onChange={handleChange} required />

        <label>Upload Supporting Document (Optional):</label>
        <input
          type="file"
          name="uploadAttachment"
          onChange={handleChange}
          accept=".pdf,.jpg,.png,.doc,.docx"
        />

        <button type="submit">Submit Report</button>
      </form>
    </div>
  );
}

export default ReportingForm;
